# Site settings
title: Elijah is awesome!
description: An awesome site for an awesome guy.
keywords: Modern, Blogging, Fun
author: Elijah
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://elijahaydn.github.io/" # the base hostname & protocol for your site
